#!/usr/bin/env python3

import os
from huggingface_hub import snapshot_download

result = snapshot_download(
    repo_id=os.environ["MODEL_ID"],
    # ignore_patterns=["*.h5", "*.bin"],  # Useful to avoid unused large files
)
